version: "3.8"

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  aspnet-api:
    build:
      context: ./aspnet-api
    container_name: aspnet_api
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres; Port=5432; Database=${POSTGRES_DB}; Username=${POSTGRES_USER}; Password=${POSTGRES_PASSWORD}"
    restart: always
    volumes:
      - ./aspnet-api/images:/app/images
    ports:
      - "8000:8000"
    entrypoint: ["/app/entrypoint.sh"]

  nextjs-app:
    build:
      context: ./nextjs-app
    container_name: nextjs_frontend
    depends_on:
      - aspnet-api
    environment:
      SERVER_API_URL: "http://aspnet-api:8000"
      NODE_ENV: "production"
    restart: always
    ports:
      - "3000:3000"

volumes:
  pg_data:
