version: "3.8"

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: postgres_dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      # Expose PostgreSQL to host for development access
      - "5432:5432"
    volumes:
      # Use the SAME volume as production to ensure data consistency
      - pg_data:/var/lib/postgresql/data
      # Optional: Mount init scripts for seeding data
      # - ./database/init:/docker-entrypoint-initdb.d:ro
    restart: always

  nginx:
    image: docker.io/library/nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf:Z
      - ./aspnet-api/images:/usr/share/nginx/html/images:ro
    # depends_on:
    #   - nextjs-app
    restart: always

volumes:
  # Use the same volume name as production
  pg_data:
